#!/bin/sh
# grep thumbs album.rss | awk -F"/" '{print $2}' | awk -F"\"" '{print $1}' >filenames
# grep "<description>" album.rss | awk -F"<description>" '{print $2}' | awk -F"</description>" '{print $1}' >./desc
# addfiles script

while IFS=$'\t' read -r fn desc rest; do 
# echo "<div class=\"card preload image square\"><a class=\"thumb\" href=\"slides/"$p"\"><img src=\"thumbs/"$p"\" width=\"212\" height=\"170\"></a></div>";
  echo "<div class=\"card preload image hascaption square\"><a class=\"thumb\" href=\"slides/"$fn"\"><img src=\"thumbs/"$fn"\" width=\"212\" height=\"170\"></a><div class=\"caption\"><div class=\"comment\">$desc  </div></div></div>"
done <./titledesc

